config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/tasks', to: 'categories#show'
  get '/map', to: 'pages#map', as: :map
  resources :transactions

  resources :categories, only: [:index]
  resources :tasks, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categories, only: [:show] do
    resources :tasks, only: [:show] do
      resources :steps, only: [:show]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tasks

   include PgSearch

  validates :name, presence: true, inclusion: { in: %w[Food Health Housekeeping Productivity Relationship Wallet] }
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :task

  include PgSearch
  pg_search_scope :global_search,
    against: [ :title, :content ],
    using: {
      tsearch: { prefix: true }
    }

  validates :title, :task, :content, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
  has_many :steps


  include PgSearch

  validates :title, :category, presence: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user

  validates :user, :description, presence: true
  validates :expense, inclusion: { in: [true, false] }
  validates :amount, presence: true, numericality: { greater_than: 0 }
  validates :category, inclusion: { in: %w[Housing Debt Transportation Food Personal Other] }
  validates :description, length: { maximum: 25 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :user_tasks
  has_many :tasks, through: :user_tasks
  has_many :transactions

  geocoded_by :location

  validates :username, presence: true, uniqueness: true, length: { minimum: 4 }
  validates :gender, inclusion: { in: [true, false] }, default: false
  validates :location, presence: true

  after_validation :geocode, if: :will_save_change_to_location?

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_task.rb
class UserTask < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :gender, :location])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :gender, :location])
  end

  protected

  def after_sign_in_path_for(resource)
    categories_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    @user = current_user
    @weather = Rails.configuration.open_weather_api.current lon: @user.longitude, lat: @user.latitude if user_signed_in?
  end

  def show
    if params[:query].present?
      @steps = Step.global_search(params[:query])
      @tasks = Task.where(steps: @steps)
    else
      @category = Category.find(params[:id])
      @tasks = Task.where(category: @category)
    end
  end
end

app/controllers/instructions_controller.rb
class InstructionsController < ApplicationController
  before_action :find_step

  def index
    @instructions = Instruction.where(step: @step)
  end

  def show
    find_instruction
  end

  private

  def find_step
    @step = Step.find(params[:step_id])
  end

  def find_instruction
    @instruction = Instruction.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end

  def map


  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_action :find_task

  def index
    @steps = Step.where(task: @task)
  end

  def show
    find_step
  end

  private

  def find_task
    @task = Task.find(params[:task_id])
  end

  def find_step
    @step = Step.find(params[:id])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_tasks, only: [:show]

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
    @steps = @task.steps
  end

  private

  def set_tasks
    @category = Category.find(params[:category_id])
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transactions
  def index
    @monthly_income = calculate_balance(false)
    @monthly_expense = calculate_balance(true)
  end

  def new
    @transaction = Transaction.new
  end

  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.user = current_user

    if @transaction.save
      redirect_to transactions_path
    else
      render :new
    end
  end

  private

  def set_transactions
    @transactions = Transaction.where(user: current_user).order(id: :desc)
  end

  def calculate_balance(expense)
    @subtransactions = @transactions.where('expense = ? AND created_at > ?', expense, 1.month.ago)
    return @subtransactions.map{ |t| t.amount }.sum
  end

  def transaction_params
    params.require(:transaction).permit(:category, :description, :amount, :date, :expense)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
# app/helpers/meta_tags_helper.rb

module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/categories/index.html.erb
<div class="weather-box" data-weather-api-key="<%= ENV['WEATHER_API_KEY'] %>">
  <% if ((@weather['main']['temp'] - 273.15).to_i) < 5 %>
    <div id="temperature">Oh my god it's<%=  (@weather['main']['temp'] - 273.15).to_i%>°C, make sure you stay warm 🔥 </div>
  <% elsif  (((@weather['main']['temp'] - 273.15).to_i) > 5) && (((@weather['main']['temp'] - 273.15).to_i) < 10) %>
    <div id="temperature">Hey it's a bit chilly <%=  (@weather['main']['temp'] - 273.15).to_i%>°C! Take your ☂️ (just in case)</div>
  <% elsif  (((@weather['main']['temp'] - 273.15).to_i) > 10) && (((@weather['main']['temp'] - 273.15).to_i) < 15)%>
    <div id="temperature">It's <%=  (@weather['main']['temp'] - 273.15).to_i%> °C! But careful with the ☀️</div>
  <% elsif  ((@weather['main']['temp'] - 273.15).to_i) > 15 %>
    <div id="temperature">Hey it's <%=  (@weather['main']['temp'] - 273.15).to_i%> °C! Wear sun screen 😎</div>
  <% end %>
</div>

<h1 style="text-align:center">Categories</h1>

<%= render 'shared/cards'%>

app/views/categories/show.html.erb
  <div class="categories">
  <h1 class="category-title"><%= @tasks.first.category.name %></h1>
  <ul class="category-tasks">
    <% @tasks.each do |task| %>
      <%= link_to category_task_path(task.category, task) do %>
      <li><%= task.title %></li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <!-- <title>Hey Mom - When in doubt, ask mom!</title> -->

    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- <link rel="stylesheet" type="text/css" href="your_website_domain/css_root/flaticon.css" > -->

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="row">
    <div class="col-xs-12 box">
        <div class="logo">
          <h1>Hey Mom</h1>
          <h4>When in doubt, ask mom!</h4>
        </div>

        <% if user_signed_in? %>
          <%= link_to categories_path do %>
            <button class="btn btn-light btn-home" style="color:white">
              Let's Start
            </button>
          <% end %>
        <% else %>
          <%= link_to new_user_session_path do %>
            <button class="btn btn-light btn-home" style="color:white">
              Log In
            </button>
          <% end %>
          <div class="sign-up">
          <p>Don't have an account yet? <%= link_to "Sign Up", new_user_registration_path %></p>
         </div>
      <% end %>
    </div>
</div>

app/views/pages/map.html.erb
<div
  id="map"
  style="width: 100%;
  height: 600px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['GOOGLE_API'] %>"
  data-longitude="<%= current_user.longitude %>"
  data-latitude="<%= current_user.latitude %>"
></div>

app/views/shared/_cards.html.erb
<div class="cards-container">
  <div class="row justify-content-center">
    <% @categories.each do |category| %>
      <%= link_to category_path(category) do %>
        <div class="col-xs-6">
        <div class="card">
            <% if category.name == "Wallet" %>
            <%= category.name %>
            <p>
              <i class="fas fa-hand-holding-usd"></i>
            </p>
            <% elsif category.name == "Food" %>
              <%= category.name %>
              <p>
                <i class="fas fa-utensils"></i>
              </p>
            <% elsif category.name == "Health" %>
              <%= category.name %>
              <p>
                <i class="fas fa-medkit"></i>
              </p>
            <% elsif category.name == "Housekeeping" %>
              <%= category.name %>
                <p>
                  <i class="fas fa-broom"></i>
                </p>
            <% elsif category.name == "Productivity" %>
              <%= category.name %>
              <p>
                <i class="fas fa-laptop"></i>
              </p>
            <% else %>
              <%= category.name %>
              <p>
                <i class="fas fa-heart"></i>
              </p>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
 <div class="navbar-wagon-item hidden-md hidden-lg">
  <div id="slide" class="dropdown">
    <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
    <div class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
      <h5 class="dropdown-title">
        <%= link_to "Hey Mom", root_path %>
      </h5>
      <div class="link-icon">
        <%= render 'shared/search' %>
      </div>
      <%= link_to categories_path do %>
        <div class="link-icon">
          <i class="fas fa-globe"></i>
          <div class="menu-name">
            All
          </div>
        </div>
      <% end %>
      <% Category.all.each do |category|%>
        <%= link_to category_path(category) do %>
          <div class="link-icon">
              <% if category.name == "Wallet" %>
                <i class="fas fa-hand-holding-usd"></i>
              <% elsif category.name == "Food" %>
                <i class="fas fa-utensils"></i>
              <% elsif category.name == "Health" %>
                <i class="fas fa-medkit"></i>
              <% elsif category.name == "Housekeeping" %>
                <i class="fas fa-broom icon-smaller"></i>
              <% elsif category.name == "Productivity" %>
                <i class="fas fa-laptop icon-smaller"></i>
              <% else %>
                <i class="fas fa-heart icon-smaller"></i>
              <% end %>
            <div class="menu-name">
              <%= category.name %>
            </div>
          </div>
        <% end %>
      <%  end %>
      <%= link_to transactions_path do%>
        <div class="link-icon">
            <i class="fas fa-money-check icon-smaller">
            </i>
            <div class="menu-name">
              Budget
            </div>
        </div>
      <% end %>
      <%= link_to destroy_user_session_path, method: :delete do %>
      <div class="link-icon">
        <i class="fas fa-sign-out-alt">
        </i>
        <div class="menu-name">
          <%= t(".sign_out", default: "Log out") %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_search.html.erb
<div id="wrap">
    <%= form_tag tasks_path, class: "form-inline", method: :get do %>
        <%= text_field_tag :query,
            params[:query],
            id: "search",
            autocomplete:"on",
            placeholder: "Search",
            value: ''
        %>
        <div id="search_submit">
        </div>
    <% end %>
</div>

app/views/steps/show.html.erb
<h1><%= @step.title %></h1>
<%= @step.content.remove(/<cite.*<\/cite>/).remove(/<a.*?>/).remove(/<\/a>/).html_safe %>

app/views/tasks/index.html.erb
<ul>
  <% @tasks.each do |task| %>
    <li><%= link_to task.title, category_task_path(task.category, task) %></li>
  <% end %>
</ul>

app/views/tasks/show.html.erb
<div class="container-fluid" style="overflow:scroll;margin-bottom:10vh;">
  <div class="top">
    <%= link_to category_path(@category) do %>
      <%= image_tag "back-arrow.png" %>
    <% end %>
  </div>

  <div class="progress-steps">
    <ul class="multi-steps">
      <% @steps.each_with_index do |step, index| %>
        <% if index == 0 %>
          <li class="is-active"><%= index + 1 %></li>
        <% else %>
          <li>&#32;</li>
        <% end %>
      <% end %>
    </ul>
  </div>
  <div class="after-progress">
    <div class="title">
      <h4><%= @task.title %></h4>
    </div>
    <div class="time-section">
      <div class="previous">
        <i class="fas fa-chevron-left fa-xs hidden" id="back-button"></i>
      </div>
      <div class="count-down">
        <p>Wanna set a timer?</p>
        <div class="timing">
          <input type="text" class="time-input" id="minute" value="" default="">
          <input type="text" class="time-input" id="second" value="" default="">
          <i class="far fa-clock" id="time-button"></i>
          <p id="timer"></p>
        </div>
      </div>
    </div>
    <div class="content">
      <div id="steps-container">
        <div id="steps" data-steps="<%= @steps.reverse.to_json %>">
          <p id="step-title" class="speech-bubble"><%= @steps.reverse.first.title %></p>
          <div class="hidden" id="step-image">
          </div>
          <p id="step-content"></p>
          <div class="hidden" id="video-content" data-youtube="<%= ENV['YOUTUBE_KEY'] %>"></div>

          <p><a id="google" class="hidden" href="">Maybe you want to google it dear.</a></p>
          <div class="bottom">
            <p class="speech-bubble hidden" id="mom-final"></p>
          </div>
          <p class="hidden" id="mom-last"></p>
          <p class="hidden" id="home-button">Well done kiddo! I'm proud of you 🤩! Wanna exit this task?</p>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="buttons">
  <button type="button" class="step-buttons" id="nope-button">Nope</button>
  <button type="button" class="step-buttons" id="yes-button">Sure</button>
</div>

app/views/transactions/_form.html.erb
<%= simple_form_for(@transaction) do |f| %>
  <%= f.input :category, collection: %w[Housing Debt Transportation Food Personal Other] %>
  <%= f.input :description %>
  <%= f.input :amount %>
  <%= f.input :date, label: "Due date", as: :string, input_html: { class: "datepicker" } %>
  <%= f.input :expense, collection: [["Expense", true], ["Income", false]], label: false %>
  <%= f.button :submit, id: "transaction-submit", class: "btn-new-budget" %>
<% end %>

app/views/transactions/index.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-6 col-sm-offset-3">
    <div class="balance-summary">
      <h1>
        Monthly Summary
        <% if @monthly_income < @monthly_expense %>
          <span class="balance-expense text-right">- $<%= (@monthly_income - @monthly_expense).abs %>
        <% else %>
          <span class="balance-income text-right">+ $<%= (@monthly_income - @monthly_expense).abs %>
        <% end %>
        </span>
      </h1>
      <div class="summary-container">
        <div>
          <div class="balance-type">Income:</div>
          <div class="balance-amount balance-income">$<%= @monthly_income %></div>
        </div>
        <div>
          <div class="balance-type">Expense:</div>
          <div class="balance-amount balance-expense">$<%= @monthly_expense %></div>
        </div>
      </div>
    </div>
    <div class="balance-container">
      <div class=balance-date>Today is <%= Date.today.strftime("%B %d, %Y") %></div>
      <% @transactions[0..7].each do |t| %>
        <div class="balance-row">
          <div class="balance-row-icon">
            <% if t.category == "Housing" %>
              <i class="fas fa-home"></i>
            <% elsif t.category == "Debt" %>
              <i class="fas fa-money-bill-wave"></i>
            <% elsif t.category == "Transportation" %>
              <i class="fas fa-bus"></i>
            <% elsif t.category == "Food" %>
              <i class="fas fa-utensils"></i>
            <% elsif t.category == "Personal" %>
              <i class="fas fa-user"></i>
            <% else %>
              <i class="fas fa-search-dollar"></i>
            <% end %>
          </div>
          <div class="balance-row-content">
            <div class="balance-row-description"><%= t.description %></div>
            <div class="balance-row-duedate"><%= t.date ? "Due: #{t.date.strftime("%b-%d")}" : " " %></div>
          </div>
          <% if t.expense == true %>
            <div class="balance-expense balance-row-amount">
          <% else %>
            <div class="balance-income balance-row-amount">
          <% end %>
            <%= t.amount %>
          </div>
        </div>
      <% end %>
      <div class="balance-new">
        <%= link_to new_transaction_path do  %>
          <i class="fas fa-plus" id="transaction-new"></i>
        <% end %>
      </div>
      <!-- <div class="transaction-form hidden">
        <%#= render "form", transaction: @transaction %>
      </div> -->

    </div>
  </div>
</div>

app/views/transactions/new.html.erb
<%= link_to transactions_path do %>
<%= image_tag "back-arrow.png" %>
<% end %>
<br>
<br>
<%= render "form" %>